version: '3.9'

services:
    assist-ai:
        build: ./server/.
        container_name: assist-ai
        volumes:
            - ./server/src/data:/app/data
            - ./server/src/config.json:/app/config.json
        ports:
            - '12345:12345'
        environment:
            - OLLAMA_URL=http://host.docker.internal:11434
        restart: always
